<a href="https://colab.research.google.com/github/WuilsonEstacio/github-para-estadistica/blob/main/Estadistica_y_probabilidad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplos en Python
Calcular los principales indicadores de la estadística descriptiva con Python es muy fácil!

https://relopezbriega.github.io/blog/2015/06/27/probabilidad-y-estadistica-con-python/

https://relopezbriega.github.io/blog/2015/06/27/probabilidad-y-estadistica-con-python/

In [ ]:
import numpy as np # importando numpy
from scipy import stats # importando scipy.stats
import pandas as pd # importando pandas

In [ ]:
datos = np.random.randn(5, 4) # datos normalmente distribuidos
datos

array([[ 0.34732361,  1.85699328, -1.90118877, -1.62021273],
       [ 0.90524183, -0.86898327,  1.33352247,  0.76442245],
       [-2.54834813,  0.19807115, -1.26874687, -0.54153809],
       [ 0.81723248, -0.59038693,  1.0223966 ,  1.48294341],
       [ 0.05968249,  0.21919668, -0.14415023, -1.63534825]])

In [ ]:
# usando pandas
dataframe = pd.DataFrame(datos, index=['a', 'b', 'c', 'd', 'e'], 
                        columns=['col1', 'col2', 'col3', 'col4'])
dataframe

col1      col2      col3      col4
a  0.347324  1.856993 -1.901189 -1.620213
b  0.905242 -0.868983  1.333522  0.764422
c -2.548348  0.198071 -1.268747 -0.541538
d  0.817232 -0.590387  1.022397  1.482943
e  0.059682  0.219197 -0.144150 -1.635348

In [ ]:
# media arítmetica
datos.mean() # Calcula la media aritmetica de

-0.10559384103383358

In [ ]:
np.mean(datos) # Mismo resultado desde la funcion de numpy

-0.10559384103383358

In [ ]:
datos.mean(axis=1) # media aritmetica de cada fila

array([-0.32927115,  0.53355087, -1.04014048,  0.68304639, -0.37515483])

In [ ]:
datos.mean(axis=0) # media aritmetica de cada columna

array([-0.08377354,  0.16297818, -0.19163336, -0.30994664])

In [ ]:
# mediana
np.median(datos) 

0.12887682071230047

In [ ]:
np.median(datos, 0) # media aritmetica de cada columna

array([ 0.34732361,  0.19807115, -0.14415023, -0.54153809])

In [ ]:
# Desviación típica
np.std(datos)

1.2034693508828012

In [ ]:
np.std(datos, 0) # Desviación típica de cada columna

array([1.27047358, 0.94937691, 1.25578476, 1.2566499 ])

In [ ]:
# varianza
np.var(datos) 

1.448338478514271

In [ ]:
np.var(datos, 0) # varianza de cada columna

array([1.61410311, 0.90131652, 1.57699538, 1.57916898])

In [ ]:
# moda
stats.mode(datos) # Calcula la moda de cada columna
# el 2do array devuelve la frecuencia.

ModeResult(mode=array([[-2.54834813, -0.86898327, -1.90118877, -1.63534825]]), count=array([[1, 1, 1, 1]]))

# Datos2

In [ ]:
# moda con pandas
datos2 = np.array([1, 2, 3, 6, 6, 1, 2, 4, 2, 2, 6, 6, 8, 10, 6])
stats.mode(datos2) # aqui la moda es el 6 porque aparece 5 veces en el vector.

ModeResult(mode=array([6]), count=array([5]))

In [ ]:
# correlacion
np.corrcoef(datos) # Crea matriz de correlación.

array([[ 1.        , -0.85323368,  0.22594411, -0.89895063,  0.63149578],
       [-0.85323368,  1.        , -0.69744767,  0.8854045 , -0.31475826],
       [ 0.22594411, -0.69744767,  1.        , -0.46479035, -0.20065142],
       [-0.89895063,  0.8854045 , -0.46479035,  1.        , -0.71198389],
       [ 0.63149578, -0.31475826, -0.20065142, -0.71198389,  1.        ]])

In [ ]:
# calculando la correlación entre dos vectores.
np.corrcoef(datos[0], datos[1])

array([[ 1.        , -0.85323368],
       [-0.85323368,  1.        ]])

In [ ]:
# covarianza
np.cov(datos) # calcula matriz de covarianza

array([[ 3.12499593, -1.45678584,  0.46743217, -1.41977442,  0.9524447 ],
       [-1.45678584,  0.93283748, -0.78832891,  0.76401783, -0.25937297],
       [ 0.46743217, -0.78832891,  1.36957453, -0.48596917, -0.20034553],
       [-1.41977442,  0.76401783, -0.48596917,  0.79821071, -0.54271713],
       [ 0.9524447 , -0.25937297, -0.20034553, -0.54271713,  0.72792926]])

In [ ]:
# covarianza de dos vectores
np.cov(datos[0], datos[1])

array([[ 3.12499593, -1.45678584],
       [-1.45678584,  0.93283748]])

In [ ]:
# usando pandas
dataframe = pd.DataFrame(datos, index=['a', 'b', 'c', 'd', 'e'], 
                        columns=['col1', 'col2', 'col3', 'col4'])
dataframe

col1      col2      col3      col4
a  0.347324  1.856993 -1.901189 -1.620213
b  0.905242 -0.868983  1.333522  0.764422
c -2.548348  0.198071 -1.268747 -0.541538
d  0.817232 -0.590387  1.022397  1.482943
e  0.059682  0.219197 -0.144150 -1.635348

In [ ]:
# resumen estadistadistico con pandas
dataframe.describe()

col1      col2      col3      col4
count  5.000000  5.000000  5.000000  5.000000
mean  -0.083774  0.162978 -0.191633 -0.309947
std    1.420433  1.061436  1.404010  1.404977
min   -2.548348 -0.868983 -1.901189 -1.635348
25%    0.059682 -0.590387 -1.268747 -1.620213
50%    0.347324  0.198071 -0.144150 -0.541538
75%    0.817232  0.219197  1.022397  0.764422
max    0.905242  1.856993  1.333522  1.482943

In [ ]:
# sumando las columnas de datos o dataframe
dataframe.sum()

col1   -0.418868
col2    0.814891
col3   -0.958167
col4   -1.549733
dtype: float64

In [ ]:
# sumando filas de datos o dataframe
dataframe.sum(axis=1)

a   -1.317085
b    2.134203
c   -4.160562
d    2.732186
e   -1.500619
dtype: float64

In [ ]:
dataframe.cumsum() # acumulados de dataframe

col1      col2      col3      col4
a  0.347324  1.856993 -1.901189 -1.620213
b  1.252565  0.988010 -0.567666 -0.855790
c -1.295783  1.186081 -1.836413 -1.397328
d -0.478550  0.595694 -0.814017  0.085615
e -0.418868  0.814891 -0.958167 -1.549733

In [ ]:
# media aritmetica de cada columna con pandas
dataframe.mean()

col1   -0.083774
col2    0.162978
col3   -0.191633
col4   -0.309947
dtype: float64

In [ ]:
# media aritmetica de cada fila con pandas
dataframe.mean(axis=1)

a   -0.329271
b    0.533551
c   -1.040140
d    0.683046
e   -0.375155
dtype: float64